networks:
  rasa-network:
    driver: bridge

services:
  rasa-actions:
    build:
      context: .
      dockerfile: Dockerfile.actions
    container_name: rasa-actions
    ports:
      - "5055:5055"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - rasa-network

  rasa-core:
    image: rasa/rasa:3.6.21
    container_name: rasa-core
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - rasa-actions
    networks:
      - rasa-network
    command: ["run", "--enable-api", "--cors", "*", "--endpoints", "endpoints.yml"]